name = "newunit"
version = "0.1.0"
license = "license"
author = "Tomohiro Degawa"
maintainer = "@degawa/newunit"
copyright = "Copyright 2023, Tomohiro Degawa"

[build]
auto-tests = true
auto-examples = true

[install]
library = true
